routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// User route
Route::group(['namespace' => 'User'], function() {
	Route::get('/', 'HomeControlle@index');
	Route::get('post', 'PostControlle@index')->name('post');
});

// Admin route
Route::group(['namespace' => 'Admin'], function() {
	Route::get('admin/home', 'HomeControlle@index')->name('admin.name');
	// User route
	Route::resource('admin/user', 'UserControlle');
	// Category route
	Route::resource('admin/category', 'CategoryController');
	// Post route
	Route::resource('admin/post', 'PostController');
	// Tag route
	Route::resource('admin/tag', 'TagController');
	// Media upload route
	Route::get('admin/media', 'MediaController@index')->name('admin.media');
});

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\User\Categories;

class CategoryController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $categories = Categories::all();
        return view('admin.category.show', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        return view('admin.category.category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        $this->validate($request, [
            'title' => 'required',
            'slug' => 'required',
        ]);

        // store 
        $category = new Categories();
        $category->name = $request->title;
        $category->slug = $request->slug;
        $category->save();

        return redirect(route('category.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $category  = Categories::where('id', $id)->first();
        return view('admin.category.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        $this->validate($request, [
            'title' => 'required',
            'slug' => 'required',
        ]);

        // update 
        $category = Categories::find($id);
        $category->name = $request->title;
        $category->slug = $request->slug;
        $category->save();

        return redirect(route('category.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        Categories::where('id', $id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/category/category.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <!-- body container start -->
    <div class="body-container">
        <div class="container-fluid">
            <div class="row">
                <!-- body header start -->
                <header class="body-header">
                    <div class="container">
                        <h3>Post</h3>
                        <nav class="submenu">
                            <ul class="float-left">
                                <li><a href="purchase-list.html">List</a></li>
                                <li><a href="" class="active">New</a></li>
                                <li><a href="purchase-find.html">Find</a></li>
                            </ul>

                            <ul class="float-right">
                                <li><a href="#">Instruction</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Print</a></li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <!-- body header end -->

                <!-- body content start -->
                <div class="container">
                    <!-- content goes to here -->
                    <h3>Create Category</h3>
                    <!-- Create the editor container -->
                    <small>Get formula help from "https://katex.org/docs/supported.html"</small>

                    @include('partial/messages')

                    <form action="{{ route('category.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="title">Category Title</label>
                                <input type="text" name="title" id="title" class="form-control" autofocus required>
                            </div>

                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="slug">Category Slug</label>
                                <input type="text" name="slug" id="slug" class="form-control" required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12">
                                <button type="submit" class="btn submit-btn float-right">Add</button>
                                <a href="{{ route('category.index') }}" class="btn reset-btn float-right">Back</a>
                            </div>
                        </div>
                    </form>

                </div>
                <!-- body content end -->
            </div>
        </div>
    </div>
    <!-- body container end -->
@endsection

@push('styles')

@endpush

@push('scripts')

@endpush

resources/views/admin/category/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <!-- body container start -->
    <div class="body-container">
        <div class="container-fluid">
            <div class="row">
                <!-- body header start -->
                <header class="body-header">
                    <div class="container">
                        <h3>Category edit</h3>
                        <nav class="submenu">
                            <ul class="float-left">
                                <li><a href="purchase-list.html">List</a></li>
                                <li><a href="" class="active">New</a></li>
                                <li><a href="purchase-find.html">Find</a></li>
                            </ul>

                            <ul class="float-right">
                                <li><a href="#">Instruction</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Print</a></li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <!-- body header end -->

                <!-- body content start -->
                <div class="container">
                    <!-- content goes to here -->
                    <h3>Create Category</h3>
                    <!-- Create the editor container -->
                    <small>Get formula help from "https://katex.org/docs/supported.html"</small>

                    @include('partial/messages')

                    <form action="{{ route('category.update', $category->id) }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}

                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="title">Category Title</label>
                                <input type="text" name="title" id="title" class="form-control" value="{{ $category->name }}" required>
                            </div>

                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="slug">Category Slug</label>
                                <input type="text" name="slug" id="slug" class="form-control" value="{{ $category->slug }}" required>
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12">
                                <button type="submit" class="btn submit-btn float-right">Update</button>
                                <a href="{{ route('category.index') }}" class="btn reset-btn float-right">Back</a>
                            </div>
                        </div>
                    </form>

                </div>
                <!-- body content end -->
            </div>
        </div>
    </div>
    <!-- body container end -->
@endsection

@push('styles')

@endpush

@push('scripts')

@endpush

resources/views/admin/category/show.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <!-- body container start -->
    <div class="body-container">
        <div class="container-fluid">
            <div class="row">
                <!-- body header start -->
                <header class="body-header">
                    <div class="container">
                        <h3>Category </h3>
                        <nav class="submenu">
                            <ul class="float-left">
                                <li><a href="purchase-list.html">List</a></li>
                                <li><a href="" class="active">New</a></li>
                                <li><a href="purchase-find.html">Find</a></li>
                            </ul>

                            <ul class="float-right">
                                <li><a href="#">Instruction</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Print</a></li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <!-- body header end -->

                <!-- body content start -->
                <div class="container">
                    <!-- list table -->
                    <div>
                        <h3>All category</h3>
                        <a href="{{ route('category.create') }}">Add new</a>
                    </div>

                    <div class="table-responsive-sm">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>SL No</th>
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th class="table-action">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach ($categories as $category)
                                    <tr>
                                        <th>{{ $loop->index + 1 }}</th>
                                        <td>{{ $category->name }}</td>
                                        <td>{{ $category->slug }}</td>
                                        <td class="table-action">
                                            <a href="{{ route('category.edit', $category->id) }}"><i class="ion-edit io-14"></i></a>

                                            <form action="{{ route('category.destroy', $category->id) }}" method="post" id="delete-form-{{ $category->id }}" style="display: none;">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>

                                            <a href="{{ route('category.index') }}" onClick="if(confirm('Are you sure, You want to delete this?')) {event.preventDefault();document.getElementById('delete-form-{{ $category->id }}').submit();} else {event.preventDefault();}"><i class="ion-android-delete io-18"></i></a>
                                        </td>
                                    </tr>
                                @endforeach

                                <tr>
                                    <th>SL No</th>
                                    <th>Name</th>
                                    <th>Slug</th>
                                    <th class="table-action">Action</th>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <!-- pagination -->
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-end">
                            <li class="page-item">
                                <a class="page-link" href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        </ul>
                    </nav>

                </div>
                <!-- body content end -->
            </div>
        </div>
    </div>
    <!-- body container end -->
@endsection

@push('styles')

@endpush

@push('scripts')

@endpush