routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// User route
Route::group(['namespace' => 'User'], function() {
	Route::get('/', 'HomeControlle@index');
	Route::get('post', 'PostControlle@index')->name('post');
});

// Admin route
Route::group(['namespace' => 'Admin'], function() {
	Route::get('admin/home', 'HomeControlle@index')->name('admin.name');
	// User route
	Route::resource('admin/user', 'UserControlle');
	// Category route
	Route::resource('admin/category', 'CategoryController');
	// Post route
	Route::resource('admin/post', 'PostController');
	// Tag route
	Route::resource('admin/tag', 'TagController');
	// Media upload route
	Route::get('admin/media', 'MediaController@index')->name('admin.media');
});

app/Http/Controllers/Admin/PostController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\User\Post;
use App\Model\User\Categories;
use App\Model\User\Tag;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $posts = Post::all();
        return view('admin.post.show', compact('posts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        $tags = Tag::all();
        $categories = Categories::all();

        return view('admin.post.post', compact('tags', 'categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
        // check validation
        $this->validate($request, [
            'title' => 'required',
            'subtitle' => 'required',
            'slug' => 'required',
            'content' => 'required',
        ]);

        // if($request->hasFile('upload')) {
        //     $image = $request->file('upload');
        //     $name = str_slug($request->title) . '.' . $image->getClientOriginalExtension();
        //     $destinationPath = public_path('/uploads/articles');
        //     $imagePath = $destinationPath. "/".  $name;
        //     $image->move($destinationPath, $name);
        //     $article->image = $name;
        // }

        // store into database 
        $post = new Post;
        $post->title = $request->title;
        $post->subtitle = $request->subtitle;
        $post->slug = $request->slug;
        $post->body = $request->content;
        $post->status = $request->publish;
        $post->save();

        $post->categories()->sync($request->categories);
        $post->tags()->sync($request->tags);

        return redirect(route('post.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        $tags = Tag::all();
        $categories = Categories::all();
        $post = Post::where('id', $id)->first();

        return view('admin.post.edit', compact('tags', 'categories', 'post'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        // check validation
        $this->validate($request, [
            'title' => 'required',
            'subtitle' => 'required',
            'slug' => 'required',
            'content' => 'required',
        ]);

        // store into database 
        $post = Post::find($id);
        $post->title = $request->title;
        $post->subtitle = $request->subtitle;
        $post->slug = $request->slug;
        $post->body = $request->content;
        $post->status = $request->publish;
        $post->save();

        return redirect(route('post.index'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id) {
        Post::where('id', $id)->delete();
        return redirect()->back();
    }
}

resources/views/admin/post/edit.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <!-- body container start -->
    <div class="body-container">
        <div class="container-fluid">
            <div class="row">
                <!-- body header start -->
                <header class="body-header">
                    <div class="container">
                        <h3>Post edit</h3>
                        <nav class="submenu">
                            <ul class="float-left">
                                <li><a href="purchase-list.html">List</a></li>
                                <li><a href="" class="active">New</a></li>
                                <li><a href="purchase-find.html">Find</a></li>
                            </ul>

                            <ul class="float-right">
                                <li><a href="#">Instruction</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Print</a></li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <!-- body header end -->

                <!-- body content start -->
                <div class="container">
                    <!-- content goes to here -->
                    <h3>Create Post</h3>
                    <!-- Create the editor container -->
                    <small>For math equation: "<strong>https://ckeditor.com/cke4/addon/mathjax</strong>"</small>
                    
                    @include('partial/messages')

                    <form action="{{ route('post.update', $post->id) }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}
                        {{ method_field('PATCH') }}

                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="title">Title</label>
                                <input type="text" name="title" id="title" class="form-control" value="{{ $post->title }}">
                            </div>

                            <div class="form-group col-md-6 col-sm-6 required">
                                <label for="subtitle">Subtitle</label>
                                <input type="text" name="subtitle" id="subtitle" class="form-control" value="{{ $post->subtitle }}">
                            </div>

                            <div class="form-group col-md-6 col-sm-6 required">
                                <label for="slug">Slug</label>
                                <input type="text" name="slug" id="slug" class="form-control" value="{{ $post->slug }}">
                            </div>

                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="editor">Content</label>
                                <textarea name="content" id="editor">{{ $post->body }}</textarea>
                            </div>

                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="file">File Import</label>
                                <input type="file" name="upload" id="file" class="form-control">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12">
                                <div class="form-check float-left">
                                    <input class="form-check-input" type="checkbox" name="publish" id="publish" @if ($post->status == 1 ) checked @endif>
                                    <label for="publish">Publish</label>
                                </div>

                                <button type="submit" name="store" class="btn submit-btn float-right">Update</button>
                                <a href="{{ route('post.index') }}" class="btn reset-btn float-right">Back</a>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- body content end -->
            </div>
        </div>
    </div>
    <!-- body container end -->
@endsection

@push('styles')
    <style type="text/css">
        .cke_screen_reader_only.cke_copyformatting_notification {display: none;}
    </style>
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ asset('admin/vendors/ckeditor/ckeditor.js') }}"></script>
    
    <script type="text/javascript">
        window.onload = function() {
            // https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html
            var editor = CKEDITOR.replace( 'editor', {
                customConfig: '/admin/js/ckeditor/ckeditor_config.js',
            } );

            // editor event
            editor.on('change', function(event) {
                console.log( 'Total bytes: ' + event.editor.getData().length );
                // console.log( event.editor.getData() );
            });
        };
    </script>
@endpush

resources/views/admin/post/post.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <!-- body container start -->
    <div class="body-container">
        <div class="container-fluid">
            <div class="row">
                <!-- body header start -->
                <header class="body-header">
                    <div class="container">
                        <h3>Post</h3>
                        <nav class="submenu">
                            <ul class="float-left">
                                <li><a href="purchase-list.html">List</a></li>
                                <li><a href="" class="active">New</a></li>
                                <li><a href="purchase-find.html">Find</a></li>
                            </ul>

                            <ul class="float-right">
                                <li><a href="#">Instruction</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Print</a></li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <!-- body header end -->

                <!-- body content start -->
                <div class="container">
                    <!-- content goes to here -->
                    <h3>Create Post</h3>
                    <!-- Create the editor container -->
                    <small>For math equation: "<strong>https://ckeditor.com/cke4/addon/mathjax</strong>"</small>
                    
                    @include('partial/messages')

                    <form action="{{ route('post.store') }}" method="post" enctype="multipart/form-data">
                        {{ csrf_field() }}

                        <div class="form-row">
                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="title">Title</label>
                                <input type="text" name="title" id="title" class="form-control">
                            </div>

                            <div class="form-group col-md-6 col-sm-6 required">
                                <label for="subtitle">Subtitle</label>
                                <input type="text" name="subtitle" id="subtitle" class="form-control">
                            </div>

                            <div class="form-group col-md-6 col-sm-6 required">
                                <label for="slug">Slug</label>
                                <input type="text" name="slug" id="slug" class="form-control">
                            </div>

                            <div class="form-group col-md-6 col-sm-6 required">
                                <label for="categories">Category</label>
                                <select name="categories[]" class="form-control" id="categories" multiple>
                                    @foreach ($categories as $category)
                                        <option value="{{ $category->id }}"> {{ $category->name }} </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group col-md-6 col-sm-6 required">
                                <label for="tags">Tag</label>
                                <select name="tags[]" class="form-control" id="tags" multiple>
                                    @foreach ($tags as $tag)
                                        <option value="{{ $tag->id }}"> {{ $tag->name }} </option>
                                    @endforeach
                                </select>
                            </div>

                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="editor">Content</label>
                                <textarea name="content" id="editor"></textarea>
                            </div>

                            <div class="form-group col-md-12 col-sm-6 required">
                                <label for="file">File Import</label>
                                <input type="file" name="upload" id="file" class="form-control">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-12">
                                <div class="form-check float-left">
                                    <input class="form-check-input" type="checkbox" name="publish" value="1" id="publish">
                                    <label for="publish">Publish</label>
                                </div>

                                <button type="submit" name="store" class="btn submit-btn float-right">Store</button>
                                <a href="{{ route('post.index') }}" class="btn reset-btn float-right">Back</a>
                            </div>
                        </div>
                    </form>
                </div>
                <!-- body content end -->
            </div>
        </div>
    </div>
    <!-- body container end -->
@endsection

@push('styles')
    <style type="text/css">
        .cke_screen_reader_only.cke_copyformatting_notification {display: none;}
    </style>
@endpush

@push('scripts')
    <script type="text/javascript" src="{{ asset('admin/vendors/ckeditor/ckeditor.js') }}"></script>
    
    <script type="text/javascript">
        window.onload = function() {
            // https://ckeditor.com/docs/ckeditor4/latest/guide/dev_installation.html
            var editor = CKEDITOR.replace( 'editor', {
                customConfig: '/admin/js/ckeditor/ckeditor_config.js',
            } );

            // editor event
            editor.on('change', function(event) {
                console.log( 'Total bytes: ' + event.editor.getData().length );
                // console.log( event.editor.getData() );
            });
        };
    </script>
@endpush

resources/views/admin/post/show.blade.php
@extends('admin.layouts.app')

@section('main-content')
    <!-- body container start -->
    <div class="body-container">
        <div class="container-fluid">
            <div class="row">
                <!-- body header start -->
                <header class="body-header">
                    <div class="container">
                        <h3>Post</h3>
                        <nav class="submenu">
                            <ul class="float-left">
                                <li><a href="purchase-list.html">List</a></li>
                                <li><a href="" class="active">New</a></li>
                                <li><a href="purchase-find.html">Find</a></li>
                            </ul>

                            <ul class="float-right">
                                <li><a href="#">Instruction</a></li>
                                <li><a href="#">Video</a></li>
                                <li><a href="#">Print</a></li>
                            </ul>
                        </nav>
                    </div>
                </header>
                <!-- body header end -->

                <!-- body content start -->
                <div class="container">
                    <!-- list table -->
                    <div>
                        <h3>All posts</h3>
                        <a href="{{ route('post.create') }}">Add new</a>
                    </div>

                    <div class="table-responsive-sm">
                        <table class="table table-bordered">
                            <thead>
                                <tr>
                                    <th>SL No</th>
                                    <th>Title</th>
                                    <th>Subtitle</th>
                                    <th>Slug</th>
                                    <th>Body</th>
                                    <th class="table-action">Action</th>
                                </tr>
                            </thead>

                            <tbody>
                                @foreach ($posts as $post)
                                    <tr>
                                        <th>{{ $loop->index + 1 }}</th>
                                        <td>{{ $post->title }}</td>
                                        <td>{{ $post->subtitle }}</td>
                                        <td>{{ $post->slug }}</td>
                                        <td>{!! $post->body !!}</td>
                                        <td class="table-action">
                                            <a href="{{ route('post.edit', $post->id) }}"><i class="ion-edit io-14"></i></a>

                                            <form action="{{ route('post.destroy', $post->id) }}" method="post" id="delete-form-{{ $post->id }}" style="display: none;">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                            </form>

                                            <a href="{{ route('post.index') }}" onClick="if(confirm('Are you sure, You want to delete this?')) {event.preventDefault();document.getElementById('delete-form-{{ $post->id }}').submit();} else {event.preventDefault();}"><i class="ion-android-delete io-18"></i></a>
                                        </td>
                                    </tr>
                                @endforeach

                                <tr>
                                    <th>SL No</th>
                                    <th>Title</th>
                                    <th>Subtitle</th>
                                    <th>Slug</th>
                                    <th>Body</th>
                                    <th class="table-action">Action</th>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <!-- pagination -->
                    <nav aria-label="Page navigation example">
                        <ul class="pagination justify-content-end">
                            <li class="page-item">
                                <a class="page-link" href="#" aria-label="Previous">
                                    <span aria-hidden="true">&laquo;</span>
                                    <span class="sr-only">Previous</span>
                                </a>
                            </li>
                            <li class="page-item"><a class="page-link" href="#">1</a></li>
                            <li class="page-item active"><a class="page-link" href="#">2</a></li>
                            <li class="page-item"><a class="page-link" href="#">3</a></li>
                            <li class="page-item">
                                <a class="page-link" href="#" aria-label="Next">
                                    <span aria-hidden="true">&raquo;</span>
                                    <span class="sr-only">Next</span>
                                </a>
                            </li>
                        </ul>
                    </nav>
                </div>
                <!-- body content end -->
            </div>
        </div>
    </div>
    <!-- body container end -->
@endsection

@push('styles')

@endpush

@push('scripts')

@endpush