routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// User route
Route::group(['namespace' => 'User'], function() {
	Route::get('/', 'HomeControlle@index');
	Route::get('post', 'PostControlle@index')->name('post');
});

// Admin route
Route::group(['namespace' => 'Admin'], function() {
	Route::get('admin/home', 'HomeControlle@index')->name('admin.name');
	// User route
	Route::resource('admin/user', 'UserControlle');
	// Category route
	Route::resource('admin/category', 'CategoryController');
	// Post route
	Route::resource('admin/post', 'PostController');
	// Tag route
	Route::resource('admin/tag', 'TagController');
	// Media upload route
	Route::get('admin/media', 'MediaController@index')->name('admin.media');
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
    <head>
        @include('admin.layouts.head')
    </head>

    <body>
        <section class="wrapper">
            @include('admin.layouts.sidebar')

            @include('admin.layouts.settings')

            <!-- body section start -->
            <div class="column body">
                @include('admin.layouts.header')

                @section('main-content')
                    @show
            </div>
            <!-- body section end -->
        </section>

        @include('admin.layouts.footer')
    </body>
</html>

resources/views/admin/layouts/footer.blade.php
<div class="wrapper-background"></div>

<!-- jQuery first, then Popper.js, then Bootstrap JS -->
{{--<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>--}}
{{--<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>--}}

<script type="text/javascript" src="{{ asset('admin/vendors/jQuery/jquery-3.3.1.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script type="text/javascript" src="{{ asset('admin/vendors/bootstrap/js/bootstrap.min.js') }}"></script>
<!-- niceScroll js -->
<script type="text/javascript" src="{{ asset('admin/vendors/jquery.nicescroll/jquery.nicescroll.min.js') }}"></script>
<!-- include js -->
<script type="text/javascript" src="{{ asset('admin/js/app.js') }}"></script>

@stack('scripts')

resources/views/admin/layouts/head.blade.php
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="csrf-token" content="{{ csrf_token() }}">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Blank page</title>
<!-- bootstrap -->
<link rel="stylesheet" href="{{ asset('admin/vendors/bootstrap/css/bootstrap.min.css') }}">
<!-- icons -->
<link rel="stylesheet" href="{{ asset('admin/vendors/ionicons/css/ionicons.min.css') }}">
<!-- google font -->
<link href="https://fonts.googleapis.com/css?family=Nunito+Sans:300,400,600" rel="stylesheet">
<!-- include style -->
<link rel="stylesheet" href="{{ asset('admin/css/master.css') }}">

@stack('styles')

resources/views/admin/layouts/header.blade.php
<!-- body nav start -->
<nav class="main-nav">
    <ul class="float-left">
        <li>
            <a href="#" id="aside-toggle"><i class="ion-android-menu io-25"></i></a>
        </li>
    </ul>

    <ul class="float-right">
        <!-- notifications -->
        <li class="dropdown">
            <a href="#" class="menu-button">
                <i class="ion-android-notifications-none io-24"></i>
            </a>
            <ul class="sub-menu">
                <li class="head">
                    <a href="#">
                        <h6>You have 2 notifications</h6>
                    </a>
                </li>
                <li><a href="#">Settings</a></li>
                <li>
                    <a href="#">
                        <span>Awesome aminmate.css</span>
                        <small>10 minit ago</small>
                    </a>
                </li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Logout</a></li>
            </ul>
        </li>

        <!-- settings -->
        <li>
            <a href="#" class="settings">
                <i class="ion-android-settings io-24"></i>
            </a>
        </li>

        <!-- profile -->
        <li class="dropdown">
            <a href="#" class="menu-button">
                <img src="{{ asset('admin/images/avatars/male-md.png') }}" alt="">
            </a>

            <ul class="sub-menu">
                <li class="head">
                    <a href="#">
                        <h6>Username</h6>
                        <small>example@gmail.com</small>
                    </a>
                </li>

                <li>
                    <a href="#">Settings</a>
                </li>

                <li>
                    <a href="#">
                        <span>Profile</span>
                        <span class="badge float-right">30%</span>
                    </a>
                </li>
                <li><a href="#">Help</a></li>
                <li><a href="#">Logout</a></li>
            </ul>
        </li>
    </ul>
</nav>
<!-- body nav end -->

resources/views/admin/layouts/settings.blade.php
<!-- settings content start -->
<div class="settings-content">
    <div class="settings-nav">
        <a href="#">
            <i class="ion-ios-close-empty settings io-24"></i>
        </a>
        <span>Settings</span>
    </div>


    <div class="slimscroll-menu settings-menu">
        <!-- Settings -->
        <hr class="mt-0" />
        <h5 class="pl-3">Basic Settings</h5>
        <hr class="mb-0" />

        <div class="p-3">
            <div class="custom-control custom-checkbox mb-2">
                <input type="checkbox" class="custom-control-input" id="notifications-check" checked>
                <label class="custom-control-label" for="notifications-check">Notifications</label>
            </div>

            <div class="custom-control custom-checkbox mb-2">
                <input type="checkbox" class="custom-control-input" id="api-access-check">
                <label class="custom-control-label" for="api-access-check">API Access</label>
            </div>

            <div class="custom-control custom-checkbox mb-2">
                <input type="checkbox" class="custom-control-input" id="auto-updates-check" checked>
                <label class="custom-control-label" for="auto-updates-check">Auto Updates</label>
            </div>

            <div class="custom-control custom-checkbox mb-2">
                <input type="checkbox" class="custom-control-input" id="online-status-check" checked>
                <label class="custom-control-label" for="online-status-check">Online Status</label>
            </div>

            <div class="custom-control custom-checkbox mb-2">
                <input type="checkbox" class="custom-control-input" id="auto-payout-check">
                <label class="custom-control-label" for="auto-payout-check">Auto Payout</label>
            </div>

        </div>


        <!-- Timeline -->
        <hr class="mt-0" />
        <h5 class="pl-3">Recent Activity</h5>
        <hr class="mb-0" />
        <div class="pl-2 pr-2">
            <div class="timeline-alt">
                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">You sold an item</a>
                        <small>Paul Burgess just purchased “Hyper - Admin Dashboard”!</small>
                        <p>
                            <small class="text-muted">5 minutes ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-airplane bg-primary-lighten text-primary timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-primary font-weight-bold mb-1 d-block">Product on the Bootstrap Market</a>
                        <small>Dave Gamache added
                            <span class="font-weight-bold">Admin Dashboard</span>
                        </small>
                        <p>
                            <small class="text-muted">30 minutes ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-microphone bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">Robert Delaney</a>
                        <small>Send you message
                            <span class="font-weight-bold">"Are you there?"</span>
                        </small>
                        <p>
                            <small class="text-muted">2 hours ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-primary-lighten text-primary timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-primary font-weight-bold mb-1 d-block">Audrey Tobey</a>
                        <small>Uploaded a photo
                            <span class="font-weight-bold">"Error.jpg"</span>
                        </small>
                        <p>
                            <small class="text-muted">14 hours ago</small>
                        </p>
                    </div>
                </div>
                <div class="timeline-item">
                    <i class="mdi mdi-microphone bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">Robert Delaney</a>
                        <small>Send you message
                            <span class="font-weight-bold">"Are you there?"</span>
                        </small>
                        <p>
                            <small class="text-muted">2 hours ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-primary-lighten text-primary timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-primary font-weight-bold mb-1 d-block">Audrey Tobey</a>
                        <small>Uploaded a photo
                            <span class="font-weight-bold">"Error.jpg"</span>
                        </small>
                        <p>
                            <small class="text-muted">14 hours ago</small>
                        </p>
                    </div>
                </div>
                <div class="timeline-item">
                    <i class="mdi mdi-microphone bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">Robert Delaney</a>
                        <small>Send you message
                            <span class="font-weight-bold">"Are you there?"</span>
                        </small>
                        <p>
                            <small class="text-muted">2 hours ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-primary-lighten text-primary timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-primary font-weight-bold mb-1 d-block">Audrey Tobey</a>
                        <small>Uploaded a photo
                            <span class="font-weight-bold">"Error.jpg"</span>
                        </small>
                        <p>
                            <small class="text-muted">14 hours ago</small>
                        </p>
                    </div>
                </div>
                <div class="timeline-item">
                    <i class="mdi mdi-microphone bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">Robert Delaney</a>
                        <small>Send you message
                            <span class="font-weight-bold">"Are you there?"</span>
                        </small>
                        <p>
                            <small class="text-muted">2 hours ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-primary-lighten text-primary timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-primary font-weight-bold mb-1 d-block">Audrey Tobey</a>
                        <small>Uploaded a photo
                            <span class="font-weight-bold">"Error.jpg"</span>
                        </small>
                        <p>
                            <small class="text-muted">14 hours ago</small>
                        </p>
                    </div>
                </div>

                <div class="timeline-item">
                    <i class="mdi mdi-upload bg-info-lighten text-info timeline-icon"></i>
                    <div class="timeline-item-info">
                        <a href="#" class="text-info font-weight-bold mb-1 d-block">You sold an item</a>
                        <small>Paul Burgess just purchased “Hyper - Admin Dashboard”!</small>
                        <p>
                            <small class="text-muted">1 day ago</small>
                        </p>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- settings content end -->

resources/views/admin/layouts/sidebar.blade.php
<!-- aside content start -->
<aside class="column aside">
    <div class="brand">
        <span>Admin Panel</span>
        <a href="#">
            <i class="ion-ios-close-empty io-24" id="aside-close"></i>
        </a>
    </div>

    <!-- aside nav start -->
    <nav class="aside-nav">
        <h6>Navigation</h6>
        <ul>
            <!-- dashboard -->
            <li id="dashboard">
                <a href="#">
                    <i class="ion-ios-timer-outline io-18"></i>
                    <span>Dashboard</span>
                </a>
            </li>

            <!-- email -->
            <li id="email">
                <a href="#">
                    <i class="ion-ios-email-outline io-17"></i>
                    <span>Email</span>
                    <span class="badge float-right">9</span>
                </a>
            </li>
        </ul>

        <h6>Components</h6>
        <ul>
            <!-- blog -->
            <li id="menu" class="dropdown">
                <a href="#" data-target="blog-option">
                    <i class="ion-ios-book-outline io-15"></i>
                    <span>Blog</span>
                    <span class="float-right">
                        <i class="ion-ios-arrow-right right io-16"></i>
                        <i class="ion-ios-arrow-down down io-16"></i>
                    </span>
                </a>

                <ul id="blog-option">
                    <li id="list"><a href="purchase-list.html">Post</a></li>
                    <li id="add-new"><a href="purchase-add.html">Category</a></li>
                    <li id="find"><a href="purchase-find.html">Tag</a></li>
                </ul>
            </li>

            <li id="post"><a href="{{ route('post.index') }}"><i class="ion-compose io-16"></i><span>Post</span></a></li>
            <li id="post"><a href="{{ route('category.index') }}"><i class="ion-ios-folder-outline io-16"></i><span>Category</span></a></li>
            <li id="post"><a href="{{ route('tag.index') }}"><i class="ion-ios-pricetags-outline io-16"></i><span>Tag</span></a></li>

            <li id="post"><a href="{{ route('admin.media') }}" target="_blank"><i class="ion-ios-people-outline io-18"></i><span>Media</span></a></li>
            <li id="post"><a href="{{ route('user.index') }}"><i class="ion-ios-people-outline io-18"></i><span>Users</span></a></li>
            

            <!-- form -->
            {{--<li id="form">--}}
                {{--<a href="#">--}}
                    {{--<i class="ion-compose io-16"></i>--}}
                    {{--<span>Form</span>--}}
                {{--</a>--}}
            {{--</li>--}}

            <!-- purchase -->
            {{--<li id="purchase" class="dropdown">--}}
                {{--<a href="#" data-target="purchase-menu">--}}
                    {{--<i class="ion-ios-cart io-17"></i>--}}
                    {{--<span>Purchase</span>--}}
                    {{--<span class="float-right">--}}
                                    {{--<i class="ion-ios-arrow-right right io-16"></i>--}}
                                    {{--<i class="ion-ios-arrow-down down io-16"></i>--}}
                                {{--</span>--}}
                {{--</a>--}}

                {{--<ul id="purchase-menu">--}}
                    {{--<li id="list"><a href="purchase-list.html">List</a></li>--}}
                    {{--<li id="add-new"><a href="purchase-add.html">Add new</a></li>--}}
                    {{--<li id="find"><a href="purchase-find.html">Find</a></li>--}}
                {{--</ul>--}}
            {{--</li>--}}

            <!-- table -->
            {{--<li id="table">--}}
                {{--<a href="#">--}}
                    {{--<i class="ion-ios-grid-view-outline io-16"></i>--}}
                    {{--<span>Table</span>--}}
                {{--</a>--}}
            {{--</li>--}}

            <!-- pages -->
            {{--<li id="pages" class="dropdown">--}}
                {{--<a href="#" data-target="purchase-menu">--}}
                    {{--<i class="ion-ios-bookmarks-outline io-16"></i>--}}
                    {{--<span>Pages</span>--}}
                    {{--<span class="float-right">--}}
                                    {{--<i class="ion-ios-arrow-right right io-16"></i>--}}
                                    {{--<i class="ion-ios-arrow-down down io-16"></i>--}}
                                {{--</span>--}}
                {{--</a>--}}

                {{--<ul id="purchase-menu">--}}
                    {{--<li id="list"><a href="purchase-list.html">List</a></li>--}}
                    {{--<li id="add-new"><a href="purchase-add.html">Add new</a></li>--}}
                    {{--<li id="find"><a href="purchase-find.html">Find</a></li>--}}
                {{--</ul>--}}
            {{--</li>--}}

            <!-- layout -->
            {{--<li id="layout" class="dropdown">--}}
                {{--<a href="#" data-target="purchase-menu">--}}
                    {{--<i class="ion-card io-16"></i>--}}
                    {{--<span>Layout</span>--}}
                    {{--<span class="float-right">--}}
                                    {{--<i class="ion-ios-arrow-right right io-16"></i>--}}
                                    {{--<i class="ion-ios-arrow-down down io-16"></i>--}}
                                {{--</span>--}}
                {{--</a>--}}

                {{--<ul id="purchase-menu">--}}
                    {{--<li id="list"><a href="purchase-list.html">List</a></li>--}}
                    {{--<li id="add-new"><a href="purchase-add.html">Add new</a></li>--}}
                    {{--<li id="find"><a href="purchase-find.html">Find</a></li>--}}
                {{--</ul>--}}
            {{--</li>--}}

            <!-- chart -->
            {{--<li id="chart">--}}
                {{--<a href="#">--}}
                    {{--<i class="ion-ios-paper-outline io-16"></i>--}}
                    {{--<span>Chaet</span>--}}
                {{--</a>--}}
            {{--</li>--}}
        </ul>

        <h6>Your Stuff</h6>
        <ul>
            <!-- profile -->
            <li id="profile">
                <a href="#">
                    <i class="ion-android-person io-16"></i>
                    <span>Profile</span>
                    <span class="badge float-right">30%</span>
                </a>
            </li>

            <!-- document -->
            <li id="documents">
                <a href="#">
                    <i class="ion-document io-17"></i>
                    <span>Documents</span>
                    <span class="badge float-right">10</span>
                </a>
            </li>
        </ul>
    </nav>
</aside>
<!-- aside content end -->